# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 303b3d408bc28cb0a43bbf893dc347c531c1e9b4c8d9600fab5ae3838ea9743457ae0d43cb8cbadb9a65acc2f184141ec0fd82c1b1907006a514871b331727ba

test:
  secret_key_base: b7054777c3bf23bd4c8f256031c10b705e74a75d8ff490ef7fbc1403540c8b2e4f7309b8196ebd8d88badcfdb09e64dafd745d7f0668e31cf8003a92c4064572

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
